---
# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

deployment:
  kind: DaemonSet

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.training.cplace.cloud`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    entryPoints:
      - websecure
    middlewares: []

ports:
  web:
    #asDefault: false
    expose: false
    redirectTo: websecure
  websecure:
    #asDefault: true
    hostPort: 443
    expose: true
    tls:
      enabled: true
    # TODO only trust load-balancer IPs
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      insecure: true

globalArguments:
  - "--global.checknewversion"

service:
  enabled: false

resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "500m"
    memory: "250Mi"
