---
# Portainer helm values
service:
  type: ClusterIP

#feature:
#  flags: ""

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

persistence:
  enabled: true
  size: "10Gi"
  storageClass: openebs-hostpath
